# In the following requests the variable $dotenv btp_baseUrl is used.
# Its value is set here.


######################## ContentFilter ########################
### ContentFilter - Get XSRF Token
# @name login
HEAD {{$dotenv btp_iflow_base_url}}/http/Pattern/ContentFilter/FilterStep
Authorization: Basic {{$dotenv btp_iflow_client_id}}:{{$dotenv btp_iflow_client_secret}}
x-csrf-token: fetch

@x-csrf-token = {{login.response.headers.x-csrf-token}}

### ContentFilter - FilterStep
POST {{$dotenv btp_iflow_base_url}}/http/Pattern/ContentFilter/FilterStep
Authorization: Basic {{$dotenv btp_iflow_client_id}}:{{$dotenv btp_iflow_client_secret}}
content-type: application/xml
x-csrf-token: {{x-csrf-token}}

<?xml version="1.0"?>
<ns0:PurchaseOrder xmlns:ns0="http://demo.sap.com/eip/content-filter" PurchaseOrderNumber="99401" OrderDate="2019-05-06">
<Address Type="Shipping">
<Name>Ellen Adams</Name>
<Street>123 Maple Street</Street>
<City>Mill Valley</City>
<State>CA</State>
<Zip>10999</Zip>
<Country>USA</Country>
</Address>
<Address Type="Billing">
<Name>Tai Yee</Name>
<Street>8 Oak Avenue</Street>
<City>Old Town</City>
<State>PA</State>
<Zip>95819</Zip>
<Country>USA</Country>
</Address>
<DeliveryNotes>Please leave packages in shed by driveway.</DeliveryNotes>
<Items>
<Item ItemNumber="10">
<ProductId>HT-1000</ProductId>
<ProductName>Notebook Basic 15</ProductName>
<Category>Notebooks</Category>
<Quantity>1</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>956.00</Price>
</Item>
<Item ItemNumber="20">
<ProductId>HT-1001</ProductId>
<ProductName>Notebook Basic 17</ProductName>
<Category>Notebooks</Category>
<Quantity>1</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>1249.00</Price>
</Item>
<Item ItemNumber="30">
<ProductId>HT-1000</ProductId>
<ProductName>Notebook Basic 15</ProductName>
<Category>Notebooks</Category>
<Quantity>1</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>956.00</Price>
</Item>
<Item ItemNumber="40">
<ProductId>HT-1030</ProductId>
<ProductName>Ergo Screen</ProductName>
<Category>Flat screens</Category>
<Quantity>2</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>460.00</Price>
</Item>
<Item ItemNumber="50">
<ProductId>HT-1101</ProductId>
<ProductName>Smart Design</ProductName>
<Category>Software</Category>
<Quantity>10</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>799.00</Price>
</Item>
</Items>
</ns0:PurchaseOrder>



### ContentFilter - MessageMapping
POST {{$dotenv btp_iflow_base_url}}/http/Pattern/ContentFilter/MessageMapping
Authorization: Basic {{$dotenv btp_iflow_client_id}}:{{$dotenv btp_iflow_client_secret}}
content-type: application/xml
x-csrf-token: {{x-csrf-token}}

<?xml version="1.0"?>
<ns0:PurchaseOrder xmlns:ns0="http://demo.sap.com/eip/content-filter" PurchaseOrderNumber="99401" OrderDate="2019-05-06">
<Address Type="Shipping">
<Name>Ellen Adams</Name>
<Street>123 Maple Street</Street>
<City>Mill Valley</City>
<State>CA</State>
<Zip>10999</Zip>
<Country>USA</Country>
</Address>
<Address Type="Billing">
<Name>Tai Yee</Name>
<Street>8 Oak Avenue</Street>
<City>Old Town</City>
<State>PA</State>
<Zip>95819</Zip>
<Country>USA</Country>
</Address>
<DeliveryNotes>Please leave packages in shed by driveway.</DeliveryNotes>
<Items>
<Item ItemNumber="10">
<ProductId>HT-1000</ProductId>
<ProductName>Notebook Basic 15</ProductName>
<Category>Notebooks</Category>
<Quantity>1</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>956.00</Price>
</Item>
<Item ItemNumber="20">
<ProductId>HT-1001</ProductId>
<ProductName>Notebook Basic 17</ProductName>
<Category>Notebooks</Category>
<Quantity>1</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>1249.00</Price>
</Item>
<Item ItemNumber="30">
<ProductId>HT-1000</ProductId>
<ProductName>Notebook Basic 15</ProductName>
<Category>Notebooks</Category>
<Quantity>1</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>956.00</Price>
</Item>
<Item ItemNumber="40">
<ProductId>HT-1030</ProductId>
<ProductName>Ergo Screen</ProductName>
<Category>Flat screens</Category>
<Quantity>2</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>460.00</Price>
</Item>
<Item ItemNumber="50">
<ProductId>HT-1101</ProductId>
<ProductName>Smart Design</ProductName>
<Category>Software</Category>
<Quantity>10</Quantity>
<CurrencyCode>EUR</CurrencyCode>
<Price>799.00</Price>
</Item>
</Items>
</ns0:PurchaseOrder>